### PR TITLE
gRPC support: ProtoBuf descriptor and grpc client

### PR DESCRIPTION
**Pull request by tiero**
~~Ideally, this PR should not be merged at all, but only to be cherry-picked in order to update the current UIs to support gRPC and Protocol Buffer service specification.~~

## Blocking 
- [x]  endpoint to fetch from the json descriptor of the `.proto` file

~~How to use it before this?~~

~~1) Generate the protobuf json descriptor running `npm run build-proto`
2) Then place somewhere in `src` folder the .json file
2.1) go [here](https://github.com/tiero/alpha-dapp/blob/master/src/index.js#L25)  and update the relative path accordingly~~

#### Update your UI to support grpc
1) In the `src/components/service` folder pick a component, eg. `alpha-example`
2) In the `callApiCallback` function add true as  **third** boolean parameter. (if false fallback to jsonRPC; it will be deprecated)

Temporary new signature: `callApiCallback(methodName, params, useGrpc)`

#### Try the fallback UI with request's fields pre-filled
__* change [this line](https://github.com/tiero/alpha-dapp/blob/master/src/index.js#L17)  from `default` to `default.grpc`__

## Considerations

If jsonRPC will be deprecated, the `callApiCallback` function can remain the same without the need of a third parameter to switch between GRPC and jsonRPC

### CODE REVIEW

**Comment by tiero** [comment]
Please review @vforvalerio87 @pennachin

**Comment by tiero** [comment]
Now we have an endpoint that fetches the json descriptor, so no needed anymore to include the json in the source code.

We should decide if deprecate the support for JSON-RPC in order to remove the third parameter from the `callApiCallback` function signature and force `default.grpc` as the default fallback UI.

cc/ @pennachin @vforvalerio87

**Comment by pennachin** [comment]
We should deprecate JSON-RPC, but let's make sure all services are updated to work with gRPC first. @ferrouswheel and @tesYolan are there any services that still need to be ported over to gRPC?

**Comment by tesYolan** [comment]
All are to be ported this week or already ported to grpc.

**Comment by ferrouswheel** [comment]
Mine are not ported yet. I could probably get them sorted early next week.

**Comment by tiero** [comment]
closing this PR in favor of #34, being sure to cherrypick commits useful not implemented in that, like custom UI generation cc/ @vforvalerio87

**Comment by vforvalerio87** [comment]
Yea I'm cherry-picking all of the custom UI stuff.
Quick notes:
- For services to work with gRPC web, [snet-daemon/pull/65](https://github.com/singnet/snet-daemon/pull/65) must be merged as it fixes a bug with CORS pre-flight requests to unregistered services
- A new daemon binary has to be produced, released
- Everybody has to update the daemon in their server

I built and deployed a fixed daemon for the SingularityNET/ExampleService box, so that already works with the new dapp PR.

Also, the matter of multiple services per service spec has to be discussed. What happens now is that some services reference a modelURI for tars with proto definitions which have multiple services in them. These definitions are shared between multiple services but a single box might implement only one of them. Either developers who have multiple services in the same service spec specify which service (or services) is available for the agent contract endpoint (and the client would allow the user to specify which service he wants to transact with), or there must be only one service per spec (my vote goes to 1 service per service spec btw). Either way, whatever we do has to be documented and explained to service developers (we can provide meaningful error messages both for the service developers and the service users in the various clients, like "please inform the guy who owns this service to fix his shit").

I suggest we continue this discussion in an issue maybe, as it's not only related to a specific PR.

**Pull request closed without merging**
